### ISSUE TITLE
TypeError: MediaWiki\Api\ApiBase::__construct(): Argument #2 ($moduleName) must be of type string, null given

### ISSUE THREAD

**Issue by gesinn-it-gea** [gesinn-it-pub/IDProvider#43]
https://github.com/gesinn-it-pub/IDProvider/actions/runs/12330981796/job/34417060212#step:4:806

If needed, drop support for MW 1.35, plan next major release.

**Comment by gesinn-it-ilm** [comment]
`TypeError` for MW 1.43 fixed. 
The error occurs because starting from MediaWiki 1.40, the `ApiBase::__construct()` method requires the `$moduleName` argument to be a non-null string. In MediaWiki 1.39 and earlier, passing null was acceptable, so the tests worked.

The support for MW 1.35 dropped. Matrix for 1.40 added in order to have codecov upload covered.
